### ISSUE TITLE
关于send_task(task_name)的问题

### ISSUE THREAD

**Issue by heyfavour** [GregaVrbancic/fastapi-celery#4]
我在启动时
celery -A example worker -l info -P eventlet
我在源码中print注册的task name，他是以example.xxx形式注册
和你在send_task(task_name)的形式并不相同，请问你是如何启动celery的能以app.celery_app.woker.exmple的形式send_task

**Comment by GregaVrbancic** [comment]
Hi @heyfavour, could you please write in English?

**Comment by heyfavour** [comment]
sry,when i run selery in windows,
user the order "celery -A example worker -l info -P eventlet"，
but i found that the task_name is example.xxxx like example.test_celery
so i coding  send_task(example.test_celery)
but in your example,you code is like  send(app.app.example.test_celery),
could u tell me how u start the celery?
why my celery task name don't contains app route?

**Comment by GregaVrbancic** [comment]
Hi, sorry, I don't have enough information about your project structure to help you. I run celery worker as presented in the readme: ```poetry run celery worker -A app.worker.celery_worker -l info -Q test-queue -c 1```
